#!/bin/sh

###############################################################################
#
# This script installs the SNS Common Library documentation. It checks to see 
# if the documentation directories exist in the source code. If they do not,
# the install is ignored.
#
# $Id$
#
###############################################################################

# FIXME: Put in error check on argument number

if [[ -d html && -d latex ]]; then
  echo "mkdir -p $1"
  mkdir -p $1	  
  echo "mkdir -p $1/latex"
  mkdir -p $1/latex
  echo "cp -r html $1"
  cp -r html $1
  echo "cp latex/*.eps $1/latex"
  cp latex/*.eps $1/latex
  echo "cp latex/*.tex $1/latex"
  cp latex/*.tex $1/latex
fi