#!/bin/sh

###############################################################################
#
# This script creates a PDF file from the SNS Common Library documentation.
#
# $Id$
#
###############################################################################

# Put in error check on argument number

cd latex
make all
mv refman.pdf $1
