/**
 * $Id$
 *
 * \file axis_manip/inc/reverse_array.hpp
 */
#ifndef _REVERSE_ARRAY_H
#define _REVERSE_ARRAY_H 1

#include <string>
#include <vector>

namespace AxisManip
{
  /**
   * \brief This function is described in section 3.11.
   *
   * This function will reorder an array so the last element of the
   * supplied is the first element of the result array.
   *
   * \param input (INPUT) is the array to be reversed
   * \param output (OUTPUT) is the reveresed array
   *
   * \param temp holds temporary memory to be passed to the function
   *
   * \return A set of warnings generated by the function
   */
  template <typename NumT>
    std::string 
    reverse_array(std::vector<NumT> const & input,
		  std::vector<NumT> & output,
		  void *temp=NULL);
  
} // AxisManip

#endif // _REVERSE_ARRAY_H
