/**
 * $Id$
 *
 * \file axis_manip/inc/rebinning.hpp
 */
#ifndef _REBINNING_H
#define _REBINNING_H 1

#include <string>
#include <vector>

namespace AxisManip
{
  /**
   * \brief This function is described in section 3.12.
   *
   * This function rebins data and its associated errors from one axis to 
   * another given axis. This function uses fractional overlap of bins to 
   * perform the rebinning process. The function also assumes that the data 
   * is represented by a histogram model.
   *   
   * This function was provided by Paul Kienzle (NIST) and is based on an 
   * OpenGenie routine.
   *   
   * \param axis_in (INPUT) is the initial data axis
   * \param input (INPUT) is the data associated with the initial axis
   * \param input_err2 (INPUT) is the square of the uncertainty associated 
   * with the data
   * \param axis_out (INPUT) is the target axis for rebinning
   * \param output (OUTPUT) is the rebinned data according to the target axis
   * \param output_err2 (OUTPUT) is the square of the uncertainty associated 
   * with the rebinned data
   *
   * \param temp holds temporary memory to be passed to the function
   *
   * \return A set of warnings generated by the function
   */
  template <typename NumT>
    std::string 
    rebin_axis_1D(std::vector<NumT> const & axis_in,
		  std::vector<NumT> const & input,
		  std::vector<NumT> const & input_err2,
		  std::vector<NumT> const & axis_out,
		  std::vector<NumT> & output,
		  std::vector<NumT> & output_err2,
		  void *temp=NULL);
  
  /**
   * \brief This function is described in section 3.13.
   */
  template <typename NumT>
    std::string 
    rebin_axis_2D(std::vector<NumT> const & axis_in_1,
		  std::vector<NumT> const & axis_in_2,
		  std::vector<NumT> const & input,
		  std::vector<NumT> const & input_err2,
		  std::vector<NumT> const & axis_out_1,
		  std::vector<NumT> const & axis_out_2,
		  std::vector<NumT> & output,
		  std::vector<NumT> & output_err2,
		  void *temp=NULL);

  /**
   * \brief This function is described in section 3.14.
   */
  template <typename NumT>
    std::string 
    rebin_axis_4D(std::vector<NumT> const & axis_in_1,
		  std::vector<NumT> const & axis_in_2,
		  std::vector<NumT> const & axis_in_3,
		  std::vector<NumT> const & axis_in_4,
		  std::vector<NumT> const & input,
		  std::vector<NumT> const & input_err2,
		  std::vector<NumT> const & axis_out_1,
		  std::vector<NumT> const & axis_out_2,
		  std::vector<NumT> const & axis_out_3,
		  std::vector<NumT> const & axis_out_4,
		  std::vector<NumT> & output,
		  std::vector<NumT> & output_err2,
		  void *temp=NULL);
  
} // AxisManip

#endif // _REBINNING_H
